version: "2"
services:
  jupyter:
    build:
     context: Jupyter
     dockerfile: Dockerfile
    volumes:
      - ./mountpoint:/home
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_started
  db:
    build:
      context: DB
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root